version: '3.8'

networks:
  store-network:
    driver: bridge

services:
  store-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store-app
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - store-network
    environment:
      DBMS_USERNAME: root
      DBMS_PASSWORD: root
      DBMS_CONNECTION: jdbc:mysql://13.209.89.241:3306/storedb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OAUTH2_GOOGLE_REDIRECT_URI: http://localhost:5173/login-success
      PAYMENT_VNPAY_RETURNURL: http://localhost:5173/order/list
    ports:
      - "8080:8080"
    restart: unless-stopped
